site_name: microBioRust docs
site_url: https://LCrossman.github.io/microBioRust/
theme:
  name: material
  font:
     text: "Open Sans"
  palette:
     - scheme: default
       toggle:
         icon: material/weather-night
         name: Switch to dark mode
       primary: custom
       accent: custom
     - scheme: slate
       toggle:
         icon: material/weather-sunny
         name: Switch to light mode
       primary: custom
       accent: custom
features:
  - navigation.tabs
custom_dir: overrides
extra_css:
  - stylesheets/extra.css
